---
title: "stacc_feb2020_enlik"
author: "Enlik Tjioe"
date: "2/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Library
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)

options(scipen = 9999)
```


# Pre-processing Data
```{r}
salesData <- read.csv("data.csv")
glimpse(salesData)
```

```{r}
salesData <- salesData %>% 
              dplyr::filter(THIRD == 1 | THIRD == 3)
salesData$THIRD <- as.factor(salesData$THIRD)
glimpse(salesData)
```

THIRD = 1
```{r}
salesFirst <- salesData %>% 
  dplyr::group_by(salesData$PRODUCER) %>% 
  dplyr::filter(THIRD == "1") %>% 
  dplyr::summarize(totalSalesFirst = sum(SALES_SUM)) %>% 
  dplyr::arrange(desc(totalSalesFirst))

salesFirst
```

THIRD = 3
```{r}
salesThird <- salesData %>% 
  dplyr::group_by(salesData$PRODUCER) %>% 
  dplyr::filter(THIRD == "3") %>% 
  dplyr::summarize(totalSalesThird = sum(SALES_SUM)) %>% 
  dplyr::arrange(desc(totalSalesThird))

salesThird
```

```{r}
df.joinSales <- dplyr::left_join(salesFirst, salesThird, by = "salesData$PRODUCER")
names(df.joinSales)[1] <- "PRODUCER"

df.salesGrowth <- df.joinSales %>% 
  group_by(PRODUCER) %>% 
  summarize(totalSalesFirst, totalSalesThird, salesGrowth = abs(round((totalSalesThird - totalSalesFirst), digits = 2))) %>% 
  arrange(desc(salesGrowth)) %>% 
  head(7)

df.salesGrowth
```

# Data Visualization
```{r}
ggplot(df.salesGrowth, aes(x = reorder(PRODUCER, -salesGrowth), y = salesGrowth)) +
  geom_bar(stat = "identity", aes(fill = salesGrowth), show.legend = F) +
  labs(title = "Total Growth Sales per Producer", x = "Producer", y = "Total Growth") +
  theme(axis.text.x = element_text(angle=90, hjust=1),
        plot.title=element_text(hjust=0.5)) +
  geom_text(aes(label = paste0(salesGrowth, " €")), vjust = -0.5) +
  ylim(0, 600)
```

