---
title: "Learn C2"
author: "Enlik"
date: "25 February 2019"
output: html_document
---

# Read Data
```{r}
sms <- read.csv("data_input/spam.csv", stringsAsFactors = FALSE, encoding = "UTF-8")
str(sms)

sms <- sms[,-c(3,4,5)]
colnames(sms) <- c("label", "text")
```

```{r}
library(tm)
```

```{r}
# VCorpus requires a source object, which can be created using VectorSource
sms.corpus <- VCorpus(VectorSource(sms$text))
# Inspecting the first 2 items in our corpus:
sms.corpus[[1]]$content
```

```{r}
sms.corpus[[2]]$content
```

```{r}
# convert all text to lower so YES == yes == Yes
sms.corpus <- tm_map(sms.corpus, content_transformer(tolower)) 
# Create a custom transformer to substitute punctuations with a space " "
transformer <- content_transformer(function(x, pattern) {
    gsub(pattern, " ", x)
})

# Remove numbers, stopwords ("am", "and", "or", "if")
sms.corpus <- tm_map(sms.corpus, removeNumbers)
sms.corpus <- tm_map(sms.corpus, removeWords, stopwords("english"))

# Substitute ".", "/", "@" and common punctuations with a white space
sms.corpus<- tm_map(sms.corpus, transformer, "/")
sms.corpus <- tm_map(sms.corpus, transformer, "@")
sms.corpus <- tm_map(sms.corpus, transformer, "-")
sms.corpus <- tm_map(sms.corpus, transformer, "\\.")

# For all other punctuations, simply strip them using the built-in function
sms.corpus.new <- tm_map(sms.corpus, removePunctuation)
```



## Decision Tree
```{r}
dat <- read.table(text ="
    Outlook Temp Humidity Windy Play
1     Sunny  Hot     High FALSE   No
2     Sunny  Hot     High  TRUE   No
3  Overcast  Hot     High FALSE  Yes
4     Rainy Mild     High FALSE  Yes
5     Rainy Cool   Normal FALSE  Yes
6     Rainy Cool   Normal  TRUE   No
7  Overcast Cool   Normal  TRUE  Yes
8     Sunny Mild     High FALSE   No
9     Sunny Cool   Normal FALSE  Yes
10    Rainy Mild   Normal FALSE  Yes
11    Sunny Mild   Normal  TRUE  Yes
12 Overcast Mild     High  TRUE  Yes
13 Overcast  Hot   Normal FALSE  Yes
14    Rainy Mild     High  TRUE   No",
                  stringsAsFactors = T)
dat$Windy <- as.factor(dat$Windy)

str(dat)
```

```{r}
round(prop.table(table(dat$Play)), 2)
```

```{r}
-0.36 * log2(0.36) - 0.64 * log2(0.64)
```

```{r}
table()
```

