---
title: "LBB Classification1"
author: "Enlik"
date: "21 February 2019"
output: 
  html_document
---


# Summmary
This LBB for Logistic Regression will use `wholesale.csv` dataset for customer segment prediction case

# Library
```{r, warning=FALSE}
# library(dplyr)
```


# Read Data
```{r}
# Read the dataset in, drop the "Region" feature because it's not interesting
wholesale <- read.csv("data_input/wholesale.csv", header=TRUE)
wholesale <- wholesale[,-2]
str(wholesale)
```

```{r}
wholesale$Industry <- factor(wholesale$Channel, levels = c(1, 2), labels = c("horeca", "retail"))

# After doing that we can remove the original Channel feature
wholesale <- wholesale[,-1]
table(wholesale$Industry)
```

```{r}
wholesale.z <- as.data.frame(scale(wholesale[,-7]))
summary(wholesale.z)
```

```{r}
wholesale.n <- as.data.frame(cbind(wholesale.z, Industry = wholesale$Industry))
summary(wholesale.n)
```

```{r}
prop.table(table(wholesale.n$Industry))
```

```{r}
set.seed(9999)
intrain <- sample(nrow(wholesale.n), nrow(wholesale.n) * 0.8)
wholesale.train <- wholesale.n[intrain, ]
wholesale.test <- wholesale.n[-intrain, ]
```

```{r}
model1 <- glm(Industry ~ Fresh + Milk + Grocery + Frozen + Detergents_Paper + Delicassen, wholesale.n, family = "binomial")

summary(model1)
```

```{r}
wholesale.test$horeca_pred <- predict(model1, wholesale.test, type = "response")

```

```{r}
predict(model1, head(wholesale.test), type = "response")
```

```{r}
predict(model1, head(wholesale.test), type = "link")
```

```{r}
predict(model1, head(wholesale.test))
```

```{r}
hist(wholesale.test$horeca_pred, breaks = 20)
```
```{r}
wholesale.test
wholesale.test[1:40, 6:8]
```

```{r}
wholesale.test$pred.isHoreca <- ifelse(wholesale.test$horeca_pred <= 0.5, 1, 0) 
table("predicted" = wholesale.test$pred.isHoreca, "actual" = wholesale.test$Industry)
```

```{r}
accu <- round((57+20)/nrow(wholesale.test), 2)
reca <- round(57/(5+57), 2)
prec <- round(57/(6+57), 2) 
spec <- round(20/(20+6), 2)

paste("Recall:", reca)
paste("Precision:", prec)
paste("Specificity:", spec)
paste("Accuracy:", accu)
```

//TODO KNN prediction method